name: Auto merge snapshot PRs

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  automerge:
    if: "${{ github.event.label.name == 'autorelease: snapshot' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Enable Pull Request Automerge
        run: |
          gh pr merge --merge || gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
