name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8

      - name: Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: qcastel/github-actions-maven-release@70725f21eb1049fbf049470e72efbcd5d1528f35
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-temurin/
        with:
          release-branch-name: main
